### ISSUE TITLE
Use pino

### ISSUE THREAD

**Issue by wheresrhys** [Financial-Times/n-logger#29]
Supposed to be superfast https://github.com/mcollina/pino

**Comment by Limess** [comment]
Had a stab at a pino wrapper for lambda as this lib didn't quite meet our needs: https://github.com/Financial-Times/lambda-logger.

A few things to note 
* it is expects streams to be piped to other processes for formatting rather than being done in the application process.
* it uses the bunyan logging format: `logger(metadata, message, ...messageFormatting)`.
* It needs some processing to convert `level` to a string rather than integer level, and adds some metadata such as `v` (pino API version) out of the box.

**Comment by rowanmanning** [comment]
We're doing this in Reliability Kit instead. [PR to track](https://github.com/Financial-Times/dotcom-reliability-kit/pull/211)
