### ISSUE TITLE
Log x-request-id

### ISSUE THREAD

**Issue by sjparkinson** [Financial-Times/n-logger#84]
We should be logging the value of the `X-Request-Id` header if available.

**Comment by kitkat119** [comment]
We have been looking into this during our Ops Cops week. The `x-request-id` header has been set in Fastly so it is now available to use in the apps. 

I found this, which looks useful: https://www.npmjs.com/package/express-http-context. It uses the module cls-hooked (https://www.npmjs.com/package/cls-hooked) to let you store request-scoped data. The idea is that this could be used to set the request id on the context in n-express and then this could be added to all logs in n-logger. Initially it made sense to do all of this in n-express so that n-logger remains agnostic but actually n-express does not expose n-logger and it always has to be required directly in the app anyway. 

Within n-logger, when creating the winston logger, you can use `winston.format.printf ` to bespoke format the logs. Then the multiple formats can be combined using `format.combine`.

Example POC:
```
const addContext = winston.format.printf(info => {
  const id = httpContext.get('id');  // Gets the request id that has been set on the context in n-express

  if (id) {
    info.id = id;
  }

  return info;
});

const logger = winston.createLogger({
  level: 'info',
  format: winston.format.combine(
    addContext,
    winston.format.simple(),
  ),
  transports: [
    new winston.transports.Console()
  ]
});
```

**Comment by rowanmanning** [comment]
This can be achieved by using [`@dotcom-reliability-kit/serialize-request`](https://github.com/Financial-Times/dotcom-reliability-kit/tree/main/packages/serialize-request#readme). We won't be adding to this library as it's likely to be replaced
